- name: Deploy Artifact
  hosts: localhost

  tasks:
    - name: Copy Artifact
      become: true
      become_user: student
      become_method: su

      copy:
        src: "/var/lib/jenkins/workspace/mvn_6/target/my-app-1.0-SNAPSHOT.jar"
        dest: "/home/student/t.jar"


